const handleHttpError = (res, error = 'Algo sucediÃ³', code = 403) => res.status(code).send({ error })


module.exports = {
    handleHttpError
}